// Per-provider bitmap dispatch for the two rendered sizes.
// Bitmaps themselves are autogenerated by firmware/tools/build_icons.py.
#pragma once
#include <cstdint>
#include "Protocol.h"
#include "icons/icons.h"

namespace stopwatch::icons {

constexpr int kSize28 = 28;   // Overview accent
constexpr int kSize96 = 96;   // Provider watermark

inline const uint8_t *bitmap28(ProviderID id) {
    switch (id) {
        case ProviderID::Codex:  return kIconCodex28;
        case ProviderID::Claude: return kIconClaude28;
        case ProviderID::Gemini: return kIconGemini28;
    }
    return nullptr;
}

inline const uint8_t *bitmap96(ProviderID id) {
    switch (id) {
        case ProviderID::Codex:  return kIconCodex96;
        case ProviderID::Claude: return kIconClaude96;
        case ProviderID::Gemini: return kIconGemini96;
    }
    return nullptr;
}

}  // namespace stopwatch::icons
