#!/usr/bin/env python3
"""
Fetch provider brand SVGs from simpleicons and emit 1-bit C headers for
LovyanGFX `drawBitmap()`. MSB-first packing, row-major, rows padded to byte.

Idempotent: re-run after editing SIZES or ICONS to regenerate headers.

Usage:
  pip install pillow requests
  brew install imagemagick      # provides `magick` for SVG rasterization
  python3 firmware/tools/build_icons.py
"""

from __future__ import annotations
import shutil, subprocess, sys
from pathlib import Path
from urllib.request import urlretrieve

from PIL import Image

ROOT     = Path(__file__).resolve().parent.parent
SVG_DIR  = ROOT / "tools" / ".cache" / "svg"
PNG_DIR  = ROOT / "tools" / ".cache" / "png"
HDR_DIR  = ROOT / "src" / "icons"

# (firmware name, simpleicons slug). Codex uses the OpenAI brand mark.
ICONS = [
    ("codex",  "openai"),
    ("claude", "claude"),
    ("gemini", "googlegemini"),
]
SIZES = [28, 96]  # 28 = Overview accent, 96 = Provider watermark

SVG_URL = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/{slug}.svg"


def fetch_svg(slug: str) -> Path:
    SVG_DIR.mkdir(parents=True, exist_ok=True)
    out = SVG_DIR / f"{slug}.svg"
    if not out.exists():
        urlretrieve(SVG_URL.format(slug=slug), out)
    return out


def rasterize(svg: Path, size: int) -> Path:
    PNG_DIR.mkdir(parents=True, exist_ok=True)
    out = PNG_DIR / f"{svg.stem}_{size}.png"
    if out.exists():
        return out
    # SimpleIcons SVGs are 24×24 solid-fill, no viewport quirks.
    # `magick` rasterizes with the default antialiasing; we threshold afterwards.
    subprocess.run(
        ["magick", "-background", "none", str(svg), "-resize", f"{size}x{size}", str(out)],
        check=True,
    )
    return out


def pack_msb(img: Image.Image) -> bytes:
    """Pack image alpha channel as 1-bit MSB-first, rows padded to byte."""
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    w, h = img.size
    pixels = img.load()
    row_bytes = (w + 7) // 8
    out = bytearray(row_bytes * h)
    for y in range(h):
        for x in range(w):
            # Use alpha as the foreground mask. Threshold > 0.5 to drop
            # antialias halo (only the icon body becomes "on").
            a = pixels[x, y][3]
            if a > 128:
                out[y * row_bytes + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def emit_header(name: str, size: int, data: bytes) -> Path:
    HDR_DIR.mkdir(parents=True, exist_ok=True)
    out = HDR_DIR / f"{name}_{size}.h"
    sym = f"kIcon{name.capitalize()}{size}"
    lines = [
        "// AUTOGENERATED by firmware/tools/build_icons.py. Do not edit by hand.",
        f"// Source: simpleicons brand mark, {size}x{size}, 1-bit MSB-first.",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"constexpr int {sym}Width  = {size};",
        f"constexpr int {sym}Height = {size};",
        f"constexpr uint8_t {sym}[] = {{",
    ]
    row_bytes = (size + 7) // 8
    for i in range(0, len(data), row_bytes):
        chunk = data[i : i + row_bytes]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += ["};", ""]
    out.write_text("\n".join(lines))
    return out


def emit_index(written: list[Path]) -> None:
    idx = HDR_DIR / "icons.h"
    lines = [
        "// AUTOGENERATED by firmware/tools/build_icons.py. Do not edit by hand.",
        "#pragma once",
        "",
    ]
    for p in sorted(written):
        lines.append(f'#include "{p.name}"')
    lines.append("")
    idx.write_text("\n".join(lines))


def main() -> int:
    if shutil.which("magick") is None:
        sys.stderr.write("error: `magick` not found. brew install imagemagick\n")
        return 1
    written: list[Path] = []
    for name, slug in ICONS:
        svg = fetch_svg(slug)
        for size in SIZES:
            png = rasterize(svg, size)
            img = Image.open(png)
            data = pack_msb(img)
            written.append(emit_header(name, size, data))
            print(f"  emit {name}_{size}.h ({len(data)} bytes)")
    emit_index(written)
    print(f"wrote {len(written)} header(s) + icons.h to {HDR_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
